AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: REST API application for Subscription Killer Web App .
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/subscription-killer-api-0.0.1-SNAPSHOT.zip
      Handler: com.matchalab.subscription_killer_api.StreamLambdaHandler::handleRequest
      Runtime: java21
      Description: Java function
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active