server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:certs/sublog-mkcert-dev-local.p12
    key-store-type: PKCS12
    key-alias: sublog-mkcert-dev-local
    key-store-password: ${SSL_PASSWORD:password}
    key-password: ${SSL_PASSWORD:password}