spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${APP_GOOGLE_CLIENT_ID}
            client-secret: ${APP_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${FRONTEND_URL}/login/oauth2/code/google
            client-authentication-method: client_secret_basic
            scope:
              - openid
              - email
              - profile
              - https://www.googleapis.com/auth/gmail.readonly
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent%20select_account
app:
  google:
    client-id: ${APP_GOOGLE_CLIENT_ID}
    client-secret: ${APP_GOOGLE_CLIENT_SECRET}
    token-server-url: https://oauth2.googleapis.com/token
    token-refresh-threshold-seconds: 300