spring:
  flyway:
    clean-disabled: false
    clean-on-validation-error: false
  sql:
    init:
      mode: always
app:
  mail:
    analysis-months: 6
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG