spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: drop-and-create
              create-target: src/main/resources/db/migration/V1__schema.sql
              drop-target: src/main/resources/db/migration/drop_all.sql
            create-source: metadata
  flyway:
    enabled: false
flyway:
  enabled: false
