set client_min_messages = WARNING;
alter table if exists email_source drop constraint if exists FKlotnr9sb2onbyr4qxorovke00;
alter table if exists google_account drop constraint if exists FKc5ldkj3kms04ke9jwyktvy1hr;
alter table if exists service_provider_alias_names drop constraint if exists FKiyof64n4vv5cbkoecjd64q4p;
alter table if exists subscription drop constraint if exists FKieobf1jy3qvggwnwgvd23vpx1;
alter table if exists subscription drop constraint if exists FK1w8ctq9rk197lhd1rtvomjyp5;
drop table if exists app_user cascade;
drop table if exists email_source cascade;
drop table if exists google_account cascade;
drop table if exists service_provider cascade;
drop table if exists service_provider_alias_names cascade;
drop table if exists subscription cascade;
set client_min_messages = WARNING;
alter table if exists email_source drop constraint if exists FKlotnr9sb2onbyr4qxorovke00;
alter table if exists google_account drop constraint if exists FKc5ldkj3kms04ke9jwyktvy1hr;
alter table if exists service_provider_alias_names drop constraint if exists FKiyof64n4vv5cbkoecjd64q4p;
alter table if exists subscription drop constraint if exists FKieobf1jy3qvggwnwgvd23vpx1;
alter table if exists subscription drop constraint if exists FK1w8ctq9rk197lhd1rtvomjyp5;
drop table if exists app_user cascade;
drop table if exists email_source cascade;
drop table if exists google_account cascade;
drop table if exists service_provider cascade;
drop table if exists service_provider_alias_names cascade;
drop table if exists subscription cascade;
